CREATE DATABASE IF NOT EXISTS coredb;
CREATE DATABASE IF NOT EXISTS classdb;
CREATE DATABASE IF NOT EXISTS admissiondb;
CREATE DATABASE IF NOT EXISTS feedb;
CREATE DATABASE IF NOT EXISTS clouddb;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
