spring.application.name=CloudinaryService
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:4410/clouddb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo_cloud}
cloudinary.api-key=${CLOUDINARY_API_KEY:123456789012345}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:demo_secret_key}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

management.endpoints.web.exposure.include=health,info
